M48
; DRILL file {KiCad 7.0.7} date Sun Oct  1 11:51:21 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-01T11:51:21+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X0.1396Y2.3831
X0.1396Y0.1381
X2.3846Y2.3831
X2.3846Y0.1581
T0
M30
